// <auto-generated />
using CozyCo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CozyCo.Data.Migrations
{
    [DbContext(typeof(CozyCoDbContext))]
    partial class CozyCoDbContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CozyCo.Domain.Models.Property", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("Address2");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Image");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.ToTable("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
